export const breadcrumbData = [
    {
        title: "Supervise Customer",
        links : [
            {
                link: "/",
                urlTitle: "Dashboard"
            },
            {
                link: "",
                urlTitle: "Supervise Customer"
            },
       ]
    }
]

export const breadcrumbDataCreate = [
    {
        title: "Create Customer",
        links : [
            {
                link: "/",
                urlTitle: "Dashboard"
            },
            {
                link: "/customer/supervise",
                urlTitle: "Supervise Customer"
            },
            {
                link: "",
                urlTitle: "Create Customer"
            },
       ]
    }
]

export const breadcrumbDataUpdate = [
    {
        title: "Update Customer",
        links : [
            {
                link: "/",
                urlTitle: "Dashboard"
            },
            {
                link: "/customer/supervise",
                urlTitle: "Supervise Customer"
            },
            {
                link: "",
                urlTitle: "Update Customer"
            },
       ]
    }
]

export const superviseData = [
    {
        fname: "Roshan",
        lname: "Syed",
        mobile: "+91 9642345291",
        email: 'roshanhanif8@gmail.com',
        city: "Bangalroe",
        state: "Karnataka",
        country: "India",
        pincode: "560037",
    },
    {
        fname: "Resham",
        lname: "Shaik",
        mobile: "+91 9642345291",
        email: 'reshaik@gmail.com',
        city: "Hyderabad",
        state: "Telangana",
        country: "India",
        pincode: "453433",
    },
    {
        fname: "Pavani",
        lname: "T",
        mobile: "+91 9642345291",
        email: 'roshanhanif8@gmail.com',
        city: "Bangalroe",
        state: "Karnataka",
        country: "India",
        pincode: "560037",
    },
    {
        fname: "Resham",
        lname: "Shaik",
        mobile: "+91 9642345291",
        email: 'reshaik@gmail.com',
        city: "Hyderabad",
        state: "Telangana",
        country: "India",
        pincode: "453433",
    },
    {
        fname: "Roshan",
        lname: "Syed",
        mobile: "+91 9642345291",
        email: 'roshanhanif8@gmail.com',
        city: "Bangalroe",
        state: "Karnataka",
        country: "India",
        pincode: "560037",
    },
    {
        fname: "Resham",
        lname: "Shaik",
        mobile: "+91 9642345291",
        email: 'reshaik@gmail.com',
        city: "Hyderabad",
        state: "Telangana",
        country: "India",
        pincode: "453433",
    },
    {
        fname: "Roshan",
        lname: "Syed",
        mobile: "+91 9642345291",
        email: 'roshanhanif8@gmail.com',
        city: "Bangalroe",
        state: "Karnataka",
        country: "India",
        pincode: "560037",
    },
    {
        fname: "Resham",
        lname: "Shaik",
        mobile: "+91 9642345291",
        email: 'reshaik@gmail.com',
        city: "Hyderabad",
        state: "Telangana",
        country: "India",
        pincode: "453433",
    },
    {
        fname: "Roshan",
        lname: "Syed",
        mobile: "+91 9642345291",
        email: 'roshanhanif8@gmail.com',
        city: "Bangalroe",
        state: "Karnataka",
        country: "India",
        pincode: "560037",
    },
    {
        fname: "Resham",
        lname: "Shaik",
        mobile: "+91 9642345291",
        email: 'reshaik@gmail.com',
        city: "Hyderabad",
        state: "Telangana",
        country: "India",
        pincode: "453433",
    },
    {
        fname: "Roshan",
        lname: "Syed",
        mobile: "+91 9642345291",
        email: 'roshanhanif8@gmail.com',
        city: "Bangalroe",
        state: "Karnataka",
        country: "India",
        pincode: "560037",
    },
    {
        fname: "Resham",
        lname: "Shaik",
        mobile: "+91 9642345291",
        email: 'reshaik@gmail.com',
        city: "Hyderabad",
        state: "Telangana",
        country: "India",
        pincode: "453433",
    },{
        fname: "Roshan",
        lname: "Syed",
        mobile: "+91 9642345291",
        email: 'roshanhanif8@gmail.com',
        city: "Bangalroe",
        state: "Karnataka",
        country: "India",
        pincode: "560037",
    },
    {
        fname: "Resham",
        lname: "Shaik",
        mobile: "+91 9642345291",
        email: 'reshaik@gmail.com',
        city: "Hyderabad",
        state: "Telangana",
        country: "India",
        pincode: "453433",
    },{
        fname: "Roshan",
        lname: "Syed",
        mobile: "+91 9642345291",
        email: 'roshanhanif8@gmail.com',
        city: "Bangalroe",
        state: "Karnataka",
        country: "India",
        pincode: "560037",
    },
    {
        fname: "Resham",
        lname: "Shaik",
        mobile: "+91 9642345291",
        email: 'reshaik@gmail.com',
        city: "Hyderabad",
        state: "Telangana",
        country: "India",
        pincode: "453433",
    },{
        fname: "Roshan",
        lname: "Syed",
        mobile: "+91 9642345291",
        email: 'roshanhanif8@gmail.com',
        city: "Bangalroe",
        state: "Karnataka",
        country: "India",
        pincode: "560037",
    },
    {
        fname: "Resham",
        lname: "Shaik",
        mobile: "+91 9642345291",
        email: 'reshaik@gmail.com',
        city: "Hyderabad",
        state: "Telangana",
        country: "India",
        pincode: "453433",
    },{
        fname: "Roshan",
        lname: "Syed",
        mobile: "+91 9642345291",
        email: 'roshanhanif8@gmail.com',
        city: "Bangalroe",
        state: "Karnataka",
        country: "India",
        pincode: "560037",
    },
    {
        fname: "Resham",
        lname: "Shaik",
        mobile: "+91 9642345291",
        email: 'reshaik@gmail.com',
        city: "Hyderabad",
        state: "Telangana",
        country: "India",
        pincode: "453433",
    },{
        fname: "Roshan",
        lname: "Syed",
        mobile: "+91 9642345291",
        email: 'roshanhanif8@gmail.com',
        city: "Bangalroe",
        state: "Karnataka",
        country: "India",
        pincode: "560037",
    },
    {
        fname: "Resham",
        lname: "Shaik",
        mobile: "+91 9642345291",
        email: 'reshaik@gmail.com',
        city: "Hyderabad",
        state: "Telangana",
        country: "India",
        pincode: "453433",
    },{
        fname: "Roshan",
        lname: "Syed",
        mobile: "+91 9642345291",
        email: 'roshanhanif8@gmail.com',
        city: "Bangalroe",
        state: "Karnataka",
        country: "India",
        pincode: "560037",
    },
    {
        fname: "Resham",
        lname: "Shaik",
        mobile: "+91 9642345291",
        email: 'reshaik@gmail.com',
        city: "Hyderabad",
        state: "Telangana",
        country: "India",
        pincode: "453433",
    },{
        fname: "Roshan",
        lname: "Syed",
        mobile: "+91 9642345291",
        email: 'roshanhanif8@gmail.com',
        city: "Bangalroe",
        state: "Karnataka",
        country: "India",
        pincode: "560037",
    },
    {
        fname: "Resham",
        lname: "Shaik",
        mobile: "+91 9642345291",
        email: 'reshaik@gmail.com',
        city: "Hyderabad",
        state: "Telangana",
        country: "India",
        pincode: "453433",
    },{
        fname: "Roshan",
        lname: "Syed",
        mobile: "+91 9642345291",
        email: 'roshanhanif8@gmail.com',
        city: "Bangalroe",
        state: "Karnataka",
        country: "India",
        pincode: "560037",
    },
    {
        fname: "Resham",
        lname: "Shaik",
        mobile: "+91 9642345291",
        email: 'reshaik@gmail.com',
        city: "Hyderabad",
        state: "Telangana",
        country: "India",
        pincode: "453433",
    },{
        fname: "Roshan",
        lname: "Syed",
        mobile: "+91 9642345291",
        email: 'roshanhanif8@gmail.com',
        city: "Bangalroe",
        state: "Karnataka",
        country: "India",
        pincode: "560037",
    },
    {
        fname: "Resham",
        lname: "Shaik",
        mobile: "+91 9642345291",
        email: 'reshaik@gmail.com',
        city: "Hyderabad",
        state: "Telangana",
        country: "India",
        pincode: "453433",
    },{
        fname: "Roshan",
        lname: "Syed",
        mobile: "+91 9642345291",
        email: 'roshanhanif8@gmail.com',
        city: "Bangalroe",
        state: "Karnataka",
        country: "India",
        pincode: "560037",
    },
    {
        fname: "Resham",
        lname: "Shaik",
        mobile: "+91 9642345291",
        email: 'reshaik@gmail.com',
        city: "Hyderabad",
        state: "Telangana",
        country: "India",
        pincode: "453433",
    },{
        fname: "Roshan",
        lname: "Syed",
        mobile: "+91 9642345291",
        email: 'roshanhanif8@gmail.com',
        city: "Bangalroe",
        state: "Karnataka",
        country: "India",
        pincode: "560037",
    },
    {
        fname: "Resham",
        lname: "Shaik",
        mobile: "+91 9642345291",
        email: 'reshaik@gmail.com',
        city: "Hyderabad",
        state: "Telangana",
        country: "India",
        pincode: "453433",
    },
]