export const breadcrumbData = [
    {
        title: "Supervise Itinerary",
        links : [
            {
                link: "/",
                urlTitle: "Dashboard"
            },
            {
                link: "",
                urlTitle: "Supervise Itinerary"
            },
       ]
    }
]

export const breadcrumbDataCreate = [
    {
        title: "Create Itinerary",
        links : [
            {
                link: "/",
                urlTitle: "Dashboard"
            },
            {
                link: "/itinerary/supervise",
                urlTitle: "Supervise Itinerary"
            },
            {
                link: "",
                urlTitle: "Create Itinerary"
            },
       ]
    }
]


export const breadcrumbDataPrepared = [
    {
        title: "Prepared Itinerary",
        links : [
            {
                link: "/",
                urlTitle: "Dashboard"
            },
            {
                link: "/itinerary/supervise",
                urlTitle: "Supervise Itinerary"
            },
            {
                link: "",
                urlTitle: "Prepared Itinerary"
            },
       ]
    }
]

export const breadcrumbDataUpdate = [
    {
        title: "Update Itinerary",
        links : [
            {
                link: "/",
                urlTitle: "Dashboard"
            },
            {
                link: "/lead-board/supervise",
                urlTitle: "Supervise Itinerary"
            },
            {
                link: "",
                urlTitle: "Update Itinerary"
            },
       ]
    }
]

export const itinerayData = [
    {
        "itinerayTitle": "Birthday Tour",
        "destination": "Hangkong",
        "typeOfHoliday": "Short Breaks",
        "adults": "10",
        "child": "5",
        "startDate": "2022-10-25",
        "endDate": "2022-10-27",
        "nights": "5",
        "travellers": "Hyderabd",
        "budgetCost": "500000",
        "costFor": "Total",
        "currency": "usd",
        "welcomeNote": "6",
        "customerName": "Roshan",
        "email": "roshan@gmail.com",
        "mobile": "909085849",
        "address": "test",
        "country": "usa",
        "state": "Talangana",
        "city": "Kurnool",
        "pincode": "558584",
        "birthDate": "2022-10-25",
        "anniversaryDate": "2022-10-26",
        "customerNote": "Customer note",
        "inclusion": "inclusion",
        "exclusion": "",
        "thankYouNote": "4",
        "cost": "cost",
        "terms": "",
        "cancellation": "",
        "tips": "tips",
        "visaInformation": "visa information",
        "itinerayNO": "HB22101157",
        "itinerayCreatedDate": "24/10/2022",
        "status": "inprogress",
        "id": 10
    },
    {
        "itinerayTitle": "Pavani Tour Pakcage",
        "destination": "Honeymoon",
        "typeOfHoliday": "Romantic / Honeymoon",
        "adults": "2",
        "child": "0",
        "startDate": "2022-10-24",
        "endDate": "2022-10-27",
        "nights": "2",
        "travellers": "Bangalore",
        "budgetCost": "10000",
        "costFor": "perCoupleCost",
        "currency": "eur",
        "welcomeNote": "5",
        "customerName": "Pavani",
        "email": "pavani@gmail.com",
        "mobile": "7878787878",
        "address": "Bangalroe",
        "country": "india",
        "state": "Karnataka",
        "city": "Kadapa",
        "pincode": "4590343",
        "birthDate": "2022-10-26",
        "anniversaryDate": "2022-10-26",
        "customerNote": "Customer Inforamation Notet",
        "inclusion": "Inclusion Text",
        "exclusion": "Exclusion Text",
        "thankYouNote": "4",
        "cost": "Cost",
        "terms": "",
        "cancellation": "Cancellation",
        "tips": "",
        "visaInformation": "",
        "itinerayNO": "HB22100959",
        "itinerayCreatedDate": "23/10/2022",
        "status": "senttocustomer",
        "id": 9
    },
    {
        "itinerayTitle": "",
        "destination": "",
        "typeOfHoliday": "",
        "adults": "",
        "child": "",
        "startDate": "",
        "endDate": "",
        "nights": "",
        "travellers": "",
        "budgetCost": "",
        "costFor": "",
        "currency": "",
        "welcomeNote": "",
        "customerName": "adfasf",
        "email": "dfdf",
        "mobile": "dfsdf",
        "address": "fsdf",
        "country": "",
        "state": "",
        "city": "",
        "pincode": "",
        "birthDate": "",
        "anniversaryDate": "",
        "customerNote": "",
        "inclusion": " adf ajkdfh adkjf hakjdf  adf ajkdfh adkjf hakjdf  adf ajkdfh adkjf hakjdf  adf ajkdfh adkjf hakjdf  adf ajkdfh adkjf hakjdf  adf ajkdfh adkjf hakjdf  adf ajkdfh adkjf hakjdf  adf ajkdfh adkjf hakjdf  adf ajkdfh adkjf hakjdf  adf ajkdfh adkjf hakjdf  adf ajkdfh adkjf hakjdf  adf ajkdfh adkjf hakjdf  adf ajkdfh adkjf hakjdf  adf ajkdfh adkjf hakjdf  adf ajkdfh adkjf hakjdf  adf ajkdfh adkjf hakjdf  adf ajkdfh adkjf hakjdf  adf ajkdfh adkjf hakjdf  adf ajkdfh adkjf hakjdf  adf ajkdfh adkjf hakjdf  adf ajkdfh adkjf hakjdf  adf ajkdfh adkjf hakjdf  adf ajkdfh adkjf hakjdf  adf ajkdfh adkjf hakjdf  adf ajkdfh adkjf hakjdf  adf ajkdfh adkjf hakjdf  adf ajkdfh adkjf hakjdf  adf ajkdfh adkjf hakjdf  adf ajkdfh adkjf hakjdf  adf ajkdfh adkjf hakjdf  adf ajkdfh adkjf hakjdf  adf ajkdfh adkjf hakjdf  adf ajkdfh adkjf hakjdf  adf ajkdfh adkjf hakjdf  adf ajkdfh adkjf hakjdf  adf ajkdfh adkjf hakjdf  adf ajkdfh adkjf hakjdf  adf ajkdfh adkjf hakjdf  adf ajkdfh adkjf hakjdf  adf ajkdfh adkjf hakjdf  adf ajkdfh adkjf hakjdf  adf ajkdfh adkjf hakjdf  adf ajkdfh adkjf hakjdf  adf ajkdfh adkjf hakjdf  adf ajkdfh adkjf hakjdf  adf ajkdfh adkjf hakjdf  adf ajkdfh adkjf hakjdf  adf ajkdfh adkjf hakjdf  adf ajkdfh adkjf hakjdf  adf ajkdfh adkjf hakjdf  adf ajkdfh adkjf hakjdf  adf ajkdfh adkjf hakjdf  adf ajkdfh adkjf hakjdf  adf ajkdfh adkjf hakjdf  adf ajkdfh adkjf hakjdf  adf ajkdfh adkjf hakjdf  adf ajkdfh adkjf hakjdf  adf ajkdfh adkjf hakjdf  adf ajkdfh adkjf hakjdf ",
        "exclusion": "",
        "thankYouNote": "",
        "cost": " adf ajkdfh adkjf hakjdf  adf ajkdfh adkjf hakjdf  adf ajkdfh adkjf hakjdf  adf ajkdfh adkjf hakjdf  adf ajkdfh adkjf hakjdf  adf ajkdfh adkjf hakjdf  adf ajkdfh adkjf hakjdf  adf ajkdfh adkjf hakjdf  adf ajkdfh adkjf hakjdf  adf ajkdfh adkjf hakjdf  adf ajkdfh adkjf hakjdf  adf ajkdfh adkjf hakjdf  adf ajkdfh adkjf hakjdf ",
        "terms": "",
        "cancellation": " adf ajkdfh adkjf hakjdf  adf ajkdfh adkjf hakjdf  adf ajkdfh adkjf hakjdf  adf ajkdfh adkjf hakjdf  adf ajkdfh adkjf hakjdf  adf ajkdfh adkjf hakjdf  adf ajkdfh adkjf hakjdf  adf ajkdfh adkjf hakjdf  adf ajkdfh adkjf hakjdf  adf ajkdfh adkjf hakjdf  adf ajkdfh adkjf hakjdf  adf ajkdfh adkjf hakjdf  adf ajkdfh adkjf hakjdf  adf ajkdfh adkjf hakjdf  adf ajkdfh adkjf hakjdf  adf ajkdfh adkjf hakjdf  adf ajkdfh adkjf hakjdf  adf ajkdfh adkjf hakjdf  adf ajkdfh adkjf hakjdf  adf ajkdfh adkjf hakjdf  adf ajkdfh adkjf hakjdf  adf ajkdfh adkjf hakjdf  adf ajkdfh adkjf hakjdf ",
        "tips": "",
        "visaInformation": "",
        "itinerayNO": "HB22100828",
        "itinerayCreatedDate": "23/10/2022",
        "status": "senttocustomer",
        "id": 7
    },
    {
        "itinerayTitle": "",
        "destination": "",
        "typeOfHoliday": "",
        "adults": "",
        "child": "",
        "startDate": "",
        "endDate": "",
        "nights": "",
        "travellers": "",
        "budgetCost": "",
        "costFor": "",
        "currency": "",
        "welcomeNote": "",
        "customerName": "dadfad",
        "email": "sfsdf",
        "mobile": "fsdfadsf",
        "address": "",
        "country": "",
        "state": "",
        "city": "",
        "pincode": "",
        "birthDate": "",
        "anniversaryDate": "",
        "customerNote": "",
        "inclusion": "",
        "exclusion": "asd",
        "thankYouNote": "2",
        "cost": "asdfadf",
        "terms": "dasdfafd",
        "cancellation": "",
        "tips": "adfadfadfs adfadfadfs adfadfadfs adfadfadfs adfadfadfs adfadfadfsadfadfadfsv adfadfadfsadfadfadfs adfadfadfs adfadfadfs adfadfadfs adfadfadfs adfadfadfsadfadfadfsv adfadfadfsadfadfadfs adfadfadfs adfadfadfs adfadfadfs adfadfadfs adfadfadfsadfadfadfsv adfadfadfsadfadfadfs adfadfadfs adfadfadfs adfadfadfs adfadfadfs adfadfadfsadfadfadfsv adfadfadfsadfadfadfs adfadfadfs adfadfadfs adfadfadfs adfadfadfs adfadfadfsadfadfadfsv adfadfadfsadfadfadfs adfadfadfs adfadfadfs adfadfadfs adfadfadfs adfadfadfsadfadfadfsv adfadfadfsadfadfadfs adfadfadfs adfadfadfs adfadfadfs adfadfadfs adfadfadfsadfadfadfsv adfadfadfsadfadfadfs adfadfadfs adfadfadfs adfadfadfs adfadfadfs adfadfadfsadfadfadfsv adfadfadfsadfadfadfs adfadfadfs adfadfadfs adfadfadfs adfadfadfs adfadfadfsadfadfadfsv adfadfadfsadfadfadfs adfadfadfs adfadfadfs adfadfadfs adfadfadfs adfadfadfsadfadfadfsv adfadfadfsadfadfadfs adfadfadfs adfadfadfs adfadfadfs adfadfadfs adfadfadfsadfadfadfsv adfadfadfsadfadfadfs adfadfadfs adfadfadfs adfadfadfs adfadfadfs adfadfadfsadfadfadfsv adfadfadfsadfadfadfs adfadfadfs adfadfadfs adfadfadfs adfadfadfs adfadfadfsadfadfadfsv adfadfadfsadfadfadfs adfadfadfs adfadfadfs adfadfadfs adfadfadfs adfadfadfsadfadfadfsv adfadfadfsadfadfadfs adfadfadfs adfadfadfs adfadfadfs adfadfadfs adfadfadfsadfadfadfsv adfadfadfsadfadfadfs adfadfadfs adfadfadfs adfadfadfs adfadfadfs adfadfadfsadfadfadfsv adfadfadfsadfadfadfs adfadfadfs adfadfadfs adfadfadfs adfadfadfs adfadfadfsadfadfadfsv adfadfadfsadfadfadfs adfadfadfs adfadfadfs adfadfadfs adfadfadfs adfadfadfsadfadfadfsv adfadfadfsadfadfadfs adfadfadfs adfadfadfs adfadfadfs adfadfadfs adfadfadfsadfadfadfsv adfadfadfsadfadfadfs adfadfadfs adfadfadfs adfadfadfs adfadfadfs adfadfadfsadfadfadfsv adfadfadfsadfadfadfs adfadfadfs adfadfadfs adfadfadfs adfadfadfs adfadfadfsadfadfadfsv adfadfadfsadfadfadfs adfadfadfs adfadfadfs adfadfadfs adfadfadfs adfadfadfsadfadfadfsv adfadfadfsadfadfadfs adfadfadfs adfadfadfs adfadfadfs adfadfadfs adfadfadfsadfadfadfsv adfadfadfsadfadfadfs adfadfadfs adfadfadfs adfadfadfs adfadfadfs adfadfadfsadfadfadfsv adfadfadfs",
        "visaInformation": "",
        "itinerayNO": "HB22100824",
        "itinerayCreatedDate": "23/10/2022",
        "status": "confirmed",
        "id": 6
    },
    {
        "itinerayTitle": "New Itinerary Title",
        "destination": "Destination",
        "typeOfHoliday": "Corporate / Event",
        "adults": "3",
        "child": "1",
        "startDate": "2022-10-24",
        "endDate": "2022-10-24",
        "nights": "2",
        "travellers": "Holiday",
        "budgetCost": "2000",
        "costFor": "perPersonCost",
        "currency": "usd",
        "welcomeNote": "11",
        "customerName": "Roshan the",
        "email": "the@the.com",
        "mobile": "848484848",
        "address": "address",
        "country": "india",
        "state": "Karnataka",
        "city": "Kadapa",
        "pincode": "453432",
        "birthDate": "2022-10-24",
        "anniversaryDate": "2022-11-02",
        "customerNote": "NOte",
        "inclusion": "inclusion new text",
        "exclusion": "exclusion new text",
        "thankYouNote": "10",
        "cost": "cost new test\nmy code add \nthe is my ne wline",
        "terms": "cost new test\nmy code add \nthe is my ne wline",
        "cancellation": "cost new test\nmy code add \nthe is my ne wlinecost new test\nmy code add \nthe is my ne wlinecost new test the is my ne wlinecost new testthe is my ne wlinecost new testthe is my ne wlinecost new test\nmy code add \nthe is my ne wline",
        "tips": "the is my ne wlinecost new testthe is my ne wlinecost new test",
        "visaInformation": "the is my ne wlinecost new testthe is my ne wlinecost new testthe is my ne wlinecost new testthe is my ne wlinecost new testthe is my ne wlinecost new testthe is my ne wlinecost new testthe is my ne wlinecost new testthe is my ne wlinecost new testthe is my ne wlinecost new testthe is my ne wlinecost new test",
        "itinerayNO": "HB22100815",
        "itinerayCreatedDate": "23/10/2022",
        "status": "inprogress",
        "id": 5
    },
    {
        "itinerayTitle": "New Itineray",
        "destination": "Banngalore",
        "typeOfHoliday": "1",
        "adults": "2",
        "child": "2",
        "startDate": "2022-10-15",
        "endDate": "2022-10-20",
        "nights": "2",
        "travellers": "2",
        "budgetCost": "10000",
        "costFor": "totalCost",
        "currency": "chf",
        "welcomeNote": "9",
        "customerName": "Pas",
        "email": "pas@gmail.com",
        "mobile": "78887878877",
        "address": "Sarjapooor",
        "country": "india",
        "state": "Talangana",
        "city": "Hyderabad",
        "pincode": "456434",
        "birthDate": "2022-10-14",
        "anniversaryDate": "2022-10-12",
        "customerNote": "pas information",
        "inclusion": "pas inclusion",
        "exclusion": "pas exclusion\n",
        "thankYouNote": "4",
        "cost": "pas cost",
        "terms": "pas terms",
        "cancellation": "pas cancellation",
        "tips": "pas tips",
        "visaInformation": "pas visa information",
        "itinerayNO": "HB22100838",
        "itinerayCreatedDate": "15/10/2022",
        "status": "rejectedCancel",
        "id": 31
    },
    {
        "itinerayTitle": "New Itineray",
        "destination": "Banngalore",
        "typeOfHoliday": "1",
        "adults": "2",
        "child": "2",
        "startDate": "2022-10-15",
        "endDate": "2022-10-20",
        "nights": "2",
        "travellers": "2",
        "budgetCost": "10000",
        "costFor": "totalCost",
        "currency": "chf",
        "welcomeNote": "9",
        "customerName": "Pas",
        "email": "pas@gmail.com",
        "mobile": "78887878877",
        "address": "Sarjapooor",
        "country": "india",
        "state": "Talangana",
        "city": "Hyderabad",
        "pincode": "456434",
        "birthDate": "2022-10-14",
        "anniversaryDate": "2022-10-12",
        "customerNote": "pas information",
        "inclusion": "pas inclusion",
        "exclusion": "pas exclusion\n",
        "thankYouNote": "4",
        "cost": "pas cost",
        "terms": "pas terms",
        "cancellation": "pas cancellation",
        "tips": "pas tips",
        "visaInformation": "pas visa information",
        "itinerayNO": "HB22100839",
        "itinerayCreatedDate": "15/10/2022",
        "status": "rejectedCancel",
        "id": 32
    },
    {
        "itinerayTitle": "New Itineray",
        "destination": "Banngalore",
        "typeOfHoliday": "1",
        "adults": "2",
        "child": "2",
        "startDate": "2022-10-15",
        "endDate": "2022-10-20",
        "nights": "2",
        "travellers": "2",
        "budgetCost": "10000",
        "costFor": "totalCost",
        "currency": "chf",
        "welcomeNote": "9",
        "customerName": "Pas",
        "email": "pas@gmail.com",
        "mobile": "78887878877",
        "address": "Sarjapooor",
        "country": "india",
        "state": "Talangana",
        "city": "Hyderabad",
        "pincode": "456434",
        "birthDate": "2022-10-14",
        "anniversaryDate": "2022-10-12",
        "customerNote": "pas information",
        "inclusion": "pas inclusion",
        "exclusion": "pas exclusion\n",
        "thankYouNote": "4",
        "cost": "pas cost",
        "terms": "pas terms",
        "cancellation": "pas cancellation",
        "tips": "pas tips",
        "visaInformation": "pas visa information",
        "itinerayNO": "HB221008300",
        "itinerayCreatedDate": "15/10/2022",
        "status": "rejectedCancel",
        "id": 33
    },
    {
        "itinerayTitle": "New Itineray",
        "destination": "Banngalore",
        "typeOfHoliday": "1",
        "adults": "2",
        "child": "2",
        "startDate": "2022-10-15",
        "endDate": "2022-10-20",
        "nights": "2",
        "travellers": "2",
        "budgetCost": "10000",
        "costFor": "totalCost",
        "currency": "chf",
        "welcomeNote": "9",
        "customerName": "Pas",
        "email": "pas@gmail.com",
        "mobile": "78887878877",
        "address": "Sarjapooor",
        "country": "india",
        "state": "Talangana",
        "city": "Hyderabad",
        "pincode": "456434",
        "birthDate": "2022-10-14",
        "anniversaryDate": "2022-10-12",
        "customerNote": "pas information",
        "inclusion": "pas inclusion",
        "exclusion": "pas exclusion\n",
        "thankYouNote": "4",
        "cost": "pas cost",
        "terms": "pas terms",
        "cancellation": "pas cancellation",
        "tips": "pas tips",
        "visaInformation": "pas visa information",
        "itinerayNO": "HB221008001",
        "itinerayCreatedDate": "15/10/2022",
        "status": "rejectedCancel",
        "id": 34
    },
    {
        "itinerayTitle": "New Itineray",
        "destination": "Banngalore",
        "typeOfHoliday": "1",
        "adults": "2",
        "child": "2",
        "startDate": "2022-10-15",
        "endDate": "2022-10-20",
        "nights": "2",
        "travellers": "2",
        "budgetCost": "10000",
        "costFor": "totalCost",
        "currency": "chf",
        "welcomeNote": "9",
        "customerName": "Pas",
        "email": "pas@gmail.com",
        "mobile": "78887878877",
        "address": "Sarjapooor",
        "country": "india",
        "state": "Talangana",
        "city": "Hyderabad",
        "pincode": "456434",
        "birthDate": "2022-10-14",
        "anniversaryDate": "2022-10-12",
        "customerNote": "pas information",
        "inclusion": "pas inclusion",
        "exclusion": "pas exclusion\n",
        "thankYouNote": "4",
        "cost": "pas cost",
        "terms": "pas terms",
        "cancellation": "pas cancellation",
        "tips": "pas tips",
        "visaInformation": "pas visa information",
        "itinerayNO": "HB221008002",
        "itinerayCreatedDate": "15/10/2022",
        "status": "rejectedCancel",
        "id": 35
    },
    {
        "itinerayTitle": "New Itineray",
        "destination": "Banngalore",
        "typeOfHoliday": "1",
        "adults": "2",
        "child": "2",
        "startDate": "2022-10-15",
        "endDate": "2022-10-20",
        "nights": "2",
        "travellers": "2",
        "budgetCost": "10000",
        "costFor": "totalCost",
        "currency": "chf",
        "welcomeNote": "9",
        "customerName": "Pas",
        "email": "pas@gmail.com",
        "mobile": "78887878877",
        "address": "Sarjapooor",
        "country": "india",
        "state": "Talangana",
        "city": "Hyderabad",
        "pincode": "456434",
        "birthDate": "2022-10-14",
        "anniversaryDate": "2022-10-12",
        "customerNote": "pas information",
        "inclusion": "pas inclusion",
        "exclusion": "pas exclusion\n",
        "thankYouNote": "4",
        "cost": "pas cost",
        "terms": "pas terms",
        "cancellation": "pas cancellation",
        "tips": "pas tips",
        "visaInformation": "pas visa information",
        "itinerayNO": "HB221008004",
        "itinerayCreatedDate": "15/10/2022",
        "status": "rejectedCancel",
        "id": 36
    }
]